#!/usr/bin/env python3

import subprocess
import os
import argparse

def main():
    parser = argparse.ArgumentParser("Run admin server")
    args = parser.parse_args()
    run_string = "nohup cmsAdminWebServer > /dev/null 2>/dev/null < /dev/null &"
    bash_string = f'bash -l -c "{run_string}"'
    subprocess.Popen([f"ssh cms-p2 '{bash_string}'"], shell=True)


if __name__ == "__main__":
    main()